server:
  port: 8080
  root-dir: static
  trusted-proxies:
    - 192.168.1.109
  proxy:
    routes:
      - base-route: /api/test
        upstream-url: https://jsonplaceholder.typicode.com

logging:
  level: INFO

rate-limiting:
  enabled: true
  requests-per-minute: 60
  burst-capacity: 100
